package com.example.appmoviljava;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/login") // This means URL's start with /demo (after Application path)
public class LoginController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private UsuarioRepository userRepository;

  @PostMapping(path="") // Map ONLY POST Requests
  public @ResponseBody String Login (@RequestBody Login usuarioLogin) {
    Usuarios usuario = userRepository.findByUsuarioPass(usuarioLogin.getCorreo(), usuarioLogin.getContraseña());
  

  if (usuario == null) {
    return "Correo o contraseña incorrecta. ";
    }
    return "El usuario" + usuario.getCorreo() + " ha iniciado sesión.";
}

}